### PR TITLE
JENKINS-42251 Add support for environment variables at deployed app

### PR DESCRIPTION
**Pull request by adoblas**
Environment variables can be defined into pipeline jobs.

### CODE REVIEW

**Comment by colin-msphere** [comment]
ok to test

**Comment by colin-msphere** [comment]
retest this please

**Comment by alexandrusavin** [comment]
retest this please

**Comment by bjarneo** [comment]
Any progress on this PR? :)

**Comment by adoblas** [comment]
Still waiting for the aproval

**Pull request merged**
