### PR TITLE
Multiple Deployments, Secret Support, and Jenkins Variable Injection

### PR DESCRIPTION
**Pull request by TheSentinel454**
I re-did the implementation of adding the multiple deployments by defining a new Post-Action step so that the previous Step can remain unchanged (wasn't sure how we could support upgrades).

I also changed the method by which the update is done to marathon to not use the Marathon Client as the way by which it does the update does not support Secrets (as well as a ton of other features within the Deployment JSON).

I added the ability to inject Jenkins Variables into the deployment ENV section.  The main reason for this was to allow for including build information in the deployment, plus we actually use this to re-deploy on each build since Marathon will not attempt to re-deploy if the deployment JSON doesn't actually change.

### CODE REVIEW

**Comment by TheSentinel454** [comment]
@colin-msphere I'm not sure what I can do about this build failure...It is saying it failed due to an invalid tag.  It **seems** like that is build configuration, but please let me know if that is not the case:

Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JavaDocs report generation: 
Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none

**Comment by colin-msphere** [comment]
Can you please rebase off of master? There is fix for the javadoc errors there.

**Comment by TheSentinel454** [comment]
@colin-msphere Sorry for the delay, should be good for review now.

**Comment by TheSentinel454** [comment]
@colin-msphere Any update on this?

**Comment by homeles** [comment]
any update on this?

**Comment by TheSentinel454** [comment]
I'm going to go ahead and close this PR.  I don't feel like having to continue to address merge conflicts.

@colin-msphere It would be nice if we could get the ability to do multiple deployments.  It seems the secrets functionality may be addressed in the new marathon client.

**Pull request closed without merging**
