### PR TITLE
Add the ability to define multiple deployments in a single job.

### PR DESCRIPTION
**Pull request by TheSentinel454**
It is common for our jobs to need to deploy more than 1 application at the completion of a job.  I've extracted out the Application-based configurations into a repeatable section to allow for multiple deployments to be done as part of a single job.

### CODE REVIEW

**Comment by ssk2** [comment]
Awesome, thank you @TheSentinel454. @colin-msphere is away for a few days, so we may be slower than usual to review.

**Comment by ssk2** [comment]
@mesosphere-ci: ok to test

**Comment by TheSentinel454** [comment]
No problem!  Is there any way for me to look at the checks that have failed?  Looks like I need some kind of login for Mesosphere?

**Comment by ssk2** [comment]
Checking.

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@TheSentinel454 @ssk2 the "[details](https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-plugin-test-pulls/28/)" link below for the Velocity test should be publicly accessible now.

**Comment by TheSentinel454** [comment]
I'm going to close this pull request as I have come up with a more upgrade friendly way of handling this.  I'll submit a new PR with those changes, as well as some other features.

**Pull request closed without merging**
